version: '3.9'

services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

  service_a:
    build:
      context: ./service_a
    ports:
      - "8082:8080"
    environment:
      - "OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans"
    depends_on:
      - zipkin

  service_b:
    build:
      context: ./service_b
    ports:
      - "8081:8081"
    environment:
      - "OTEL_EXPORTER_ZIPKIN_ENDPOINT=http://zipkin:9411/api/v2/spans"
    depends_on:
      - zipkin
